config/routes.rb
Rails.application.routes.draw do
  resources :passwords, controller: "clearance/passwords", only: [:create, :new]
  resource :session, controller: "clearance/sessions", only: [:create]
  root "welcome#index"
  resources :users, controller: "users", only: [:create, :edit] do
    resource :password,
      controller: "clearance/passwords",
      only: [:create, :edit, :update]
  end

 resources :listings do 
   resources :reservations
  end 

  resources :users 
    # resources :listings, only: [:create, :new, :edit, :destroy, :show]



  get "/sign_in" => "clearance/sessions#new", as: "sign_in"
  delete "/sign_out" => "clearance/sessions#destroy", as: "sign_out"
  get "/sign_up" => "clearance/users#new", as: "sign_up"
  get "/auth/:provider/callback" => "sessions#create_from_omniauth"
  post "verification/:id" => "listings#verify", as: "verify"
  post "/listings/:listing_id/reservations/:id" => "reservations#destroy", as: "delete"
  post "/listings/:listing_id/reservations/:id/checkout" => "reservations#checkout", as: "checkout"

 post "/search"  => "listings#search"

  get 'braintree/new'
  post 'braintree/checkout'
  post 'braintree/new'




  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/listing.rb
class Listing < ApplicationRecord
  belongs_to :user
  mount_uploader :avatar, AvatarUploader
  has_many :reservations
 
  scope :location, -> (a) {where("location ILIKE ?", "%#{a}%")}

  scope :min_price, -> (a) {where("price > ?", a)}
  scope :max_price, -> (a) {where("price < ?", a)}

  # def self.location(a)
  #   where(location: a)
  # end 

  # Listing.location("tokyo")

  # def self.minimum(a)
  #   where(price > 50)
  # end 


  # def self.maximum(100)
  #   where.(price < 100)
  # end 




end

app/controllers/listings_controller.rb
class ListingsController < ApplicationController
	def new
		@user = params[:user_id]
		@listing = Listing.new
		render template: "listings/new"
	end

	def create
	   @listing = current_user.listings.new(listings_params)
	   if @listing.save
		   redirect_to listing_path(@listing)
		   flash[:notice] = "you have successfully created your listing"
		else
			 flash[:notice] = "you have failed to create your listing"
			 redirect_to new_listing_path(@user, @listing)		
		end 
	end 

	def show
		@listing = Listing.find(params[:id]) 
		render template: "listings/show"
	end

  def edit
	  @listing = Listing.find(params[:id])	  
  end

  def update
  	@listing = Listing.find(params[:id])
	  if @listing.update(listings_params)
	  	redirect_to listing_path(@listing)
	  else 
	    redirect_to edit_listing_path(@listing)
	  flash[:notice] = "edit failed"
	  end  	
  end

	def search 
		@listings = Listing.where(nil)
		filtering_params(params).each do |key, value|
			@listings = @listings.public_send(key,value) if value.present?
		end

		@json_listings = @listings.map do |x|
			x.location
		end
		@json_listings = @json_listings.uniq


 		# [<#Listing lskdjf ittle: >, <#LIsting
		# ["oslo", "norway"]
		respond_to do |format|
			format.html 
			format.json { render json: @json_listings }
		end

	
	 #  if !params[:location].nil?
	 #  @listings = Listing.location(params[:location])
		# end

	 #  if !params[:max_price].nil? && !params[:max_price].nil? 
	 #  	@listings = Listing.all
	 #  	byebug
	 #  	# if !params[:max_price].nil? || !params[:min_price].nil?
	 #  	@listings = @listings.max_price(filtering_params)
	 #  	@listings = @listings.min_price(filtering_params)
	 #  	# end 
	 #  	# if !params[:max_price].nil? || params[:min_price].nil?
	 # 		 # @listings = @listings.max_price(params[:max_price])
	 # 		# else !params[:min_price].nil? || params[:max_price].nil?
		#   # @listings = @listings.min_price(params[:min_price])
		# 	# end 
	 #  end 

	 #  render template: "listings/search" 
	end 

	def verify
		@listing = Listing.find(params[:id])
		@listing.verified = true
		@listing.save
		flash[:notice] = "you verified this listing"
		redirect_to listing_path(@listing)
	end

	def destroy
	@listing = Listing.find(params[:id])
	@listing.destroy
	flash[:notice] = "the listing was deleted"
	redirect_to root_path
	end

private 

	def listings_params
		params.require(:listing).permit(:title, :price, :location, :avatar)
	end

	def filtering_params(params)
		params.slice(:location, :max_price, :min_price)
		
	end
end

app/helpers/listings_helper.rb
module ListingsHelper
end

app/views/listings/_form.html.erb
<div class="text-field">
  <%= form.label :title %>
  <%= form.text_field :title %>
</div>

<div class="text-field">
  <%= form.label :price %>
  <%= form.text_field :price %>
</div>

<div class="text-field">
  <%= form.label :location %>
  <%= form.text_field :location %>
</div>


<div class="text-field">
  <%= form.label :image %>
  <%= form.file_field :avatar %>
</div>

app/views/listings/edit.html.erb
<div class="flex-wrap">
    <div class="d-flex justify-content-center flex-wrap">

      <%= form_for @listing do |form| %>
      <%= render partial: '/listings/form', object: form %>
  <br>
        <%= form.submit%>
    </div>

    <br>
    
    <% end %>
  
</div>

app/views/listings/new.html.erb
<br> <br> <br> <br>


  <div class="flex-wrap">
    <div class="d-flex justify-content-center flex-wrap">

      <%= form_for @listing do |form| %>
      <%= render partial: '/listings/form', object: form %>
  <br>
        <%= form.submit%>
    </div>

    <br>
    
    <% end %>
  
</div>

app/views/listings/search.html.erb
</br>

</br></br></br>

<div class="d-flex"> 
<div style="margin: auto">

<% @listings.each do |listing| %>

  <%= image_tag listing.avatar.url if listing.avatar? %> 
  <br>
  <br>

  <div> 
    <%= listing.title %> 
    </br> 
  </div>

  $<%=listing.price %> per night</br>

  <%=listing.location %> </br></br></br>

  <div class="row">
    <%= button_to "verify", verify_path(listing), method: :post%>
    <%= button_to "reserve",new_listing_reservation_path(listing), method: :get
    %>
    <%= button_to "edit", edit_listing_path(listing), method: :get%>
    <%= button_to "delete", listing_path(listing), method: :delete%>
  </div>
  


<%end%>

</div>
    </div>

app/views/listings/show.html.erb
</br></br>

<div class="d-flex"> 
<div style="margin: auto">

<%= image_tag @listing.avatar.medium.url if @listing.avatar? %> <br>
</br>
<div> <%= @listing.title %> </br> </div>


$<%=@listing.price %> per night</br>

<%= @listing.location %> </br></br></br>

<div class="row">
<%= button_to "verify", verify_path(@listing), method: :post%>

<%= button_to "reserve", new_listing_reservation_path(@listing), method: :get
%>

<%= button_to "edit", edit_listing_path(@listing), method: :get%>
</div>
</br></br>
<%= button_to "delete", listing_path(@listing), method: :delete%>

</div>
</div>