config/routes.rb
Rails.application.routes.draw do
  resources :passwords, controller: "clearance/passwords", only: [:create, :new]
  resource :session, controller: "clearance/sessions", only: [:create]
  root "welcome#index"
  resources :users, controller: "users", only: [:create, :edit] do
    resource :password,
      controller: "clearance/passwords",
      only: [:create, :edit, :update]
  end

 resources :listings do 
   resources :reservations
  end 

  resources :users 
    # resources :listings, only: [:create, :new, :edit, :destroy, :show]



  get "/sign_in" => "clearance/sessions#new", as: "sign_in"
  delete "/sign_out" => "clearance/sessions#destroy", as: "sign_out"
  get "/sign_up" => "clearance/users#new", as: "sign_up"
  get "/auth/:provider/callback" => "sessions#create_from_omniauth"
  post "verification/:id" => "listings#verify", as: "verify"
  post "/listings/:listing_id/reservations/:id" => "reservations#destroy", as: "delete"
  post "/listings/:listing_id/reservations/:id/checkout" => "reservations#checkout", as: "checkout"

 post "/search"  => "listings#search"

  get 'braintree/new'
  post 'braintree/checkout'
  post 'braintree/new'




  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
	def index
		@user = current_user
        #listing.user
        #listing.reservations
		@listings = Listing.includes(:user, :reservations).all
    
    # @listings_uniq = @listings.uniq! 
    # @json_listings = @listings.map do |x|
    #   x.location 
    # end
    arr = []
    @listings.each do |l| 
      arr << l.location.to_s 
    end 
    arr = arr.uniq 
    puts arr 
    @json_listings = arr 

    respond_to do |format|
      format.html 
      format.json { render json: @json_listings }
    end
	end	
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/welcome/index.html.erb
    <br>

<div class="d-flex justify-content-center flex-wrap">

<br><br>
    <h1> Homes </h1>

</div>

<br><br>
  
<div class="d-flex justify-content-center flex-wrap">
    <% @listings.each do |listing| %> 

      	<div class="card" style="width: 27rem; border: none; margin-bottom: 2vw">

      	   <div class="card-body" style='text-align: center;'>

          <%= image_tag listing.avatar.small.url if listing.avatar?  %> <br><br>

           <h4 class="card-title" style="text-align: center"> <%= listing.title %>
      	   
           <h6 class="card-title" style="text-align: center"> <%= listing.location %> 
           </h6>
 
           <div class="card-title" style="text-align: center">

           <p>$<%= listing.price %> per night</p>
             
           <p><%= listing.user.name %></p>
           <p><%= listing.reservations.size %></p>
           </div>
           
           <div class="card-title" style="text-align: center"> <%= link_to "See Listing", listing_path(listing.id), class: "btn btn-primary" %> </div>
           </div>
      	
        </div>
    	
      <br>
    
    <% end %>

</div>