config/routes.rb
Rails.application.routes.draw do
  resources :passwords, controller: "clearance/passwords", only: [:create, :new]
  resource :session, controller: "clearance/sessions", only: [:create]
  root "welcome#index"
  resources :users, controller: "users", only: [:create, :edit] do
    resource :password,
      controller: "clearance/passwords",
      only: [:create, :edit, :update]
  end

 resources :listings do 
   resources :reservations
  end 

  resources :users 
    # resources :listings, only: [:create, :new, :edit, :destroy, :show]



  get "/sign_in" => "clearance/sessions#new", as: "sign_in"
  delete "/sign_out" => "clearance/sessions#destroy", as: "sign_out"
  get "/sign_up" => "clearance/users#new", as: "sign_up"
  get "/auth/:provider/callback" => "sessions#create_from_omniauth"
  post "verification/:id" => "listings#verify", as: "verify"
  post "/listings/:listing_id/reservations/:id" => "reservations#destroy", as: "delete"
  post "/listings/:listing_id/reservations/:id/checkout" => "reservations#checkout", as: "checkout"

 post "/search"  => "listings#search"

  get 'braintree/new'
  post 'braintree/checkout'
  post 'braintree/new'




  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/reservation.rb
class Reservation < ApplicationRecord
  belongs_to :user
  belongs_to :listing
end

app/controllers/reservations_controller.rb
class ReservationsController < ApplicationController

  before_action :require_login

  def new 
    @reservation = Reservation.new
    @listing = Listing.find(params[:listing_id])
    render template: "reservations/new"
  end
  
  def create 
    @listing = Listing.find(params[:listing_id])
    @reservation = current_user.reservations.new(reservation_params)
    @reservation.listing_id = @listing.id
    @reservation.total_price = ((@reservation.check_out - @reservation.check_in) * @reservation.listing.price).to_i
    if @reservation.save
       redirect_to [@listing, @reservation]
     else
       redirect_to new_listing_reservation(@listing)
    end
  end
  
  def show
    @listing = Listing.find(params[:listing_id])
    @reservation = Reservation.find(params[:id])
    @client_token = Braintree::ClientToken.generate
  end
  
  def destroy
  @reservation = Reservation.find(params[:id])
  @reservation.destroy
  flash[:notice] = "the reservation was canceled"
  redirect_to root_path
  end


  def checkout

  nonce_from_the_client = params[:checkout_form][:payment_method_nonce]

  result = Braintree::Transaction.sale(
   :amount => "10.00", #this is currently hardcoded
   :payment_method_nonce => nonce_from_the_client,
   :options => {
      :submit_for_settlement => true
    }
   )

  if result.success?

    @listing = Listing.find(params[:listing_id])
    @reservation = Reservation.find(params[:id])
     ReservationMailer.booking_email(current_user, @listing.user, @reservation.id).deliver_later
     # @listing = Listing.find(params[:listing_id])
     # @reservation= Reservation.find(params[:id])
    redirect_to :root, :flash => { :success => "Transaction successful!" }
  else
    redirect_to :root, :flash => { :error => "Transaction failed. Please try again." }
  end
  end

  private

  def reservation_params
    params.require(:reservation).permit(:check_in, :check_out)
  end 


end

app/helpers/reservations_helper.rb
module ReservationsHelper
end

app/views/reservations/_form.html.erb
<br><br><br>

<div class="text-field">
  <%= f.label :check_in %>
  <%= f.text_field :check_in, placeholder: "      dd/mm/yy", id:"add_flatpicker", style:"width:10vw;"%>
</div>

<br> 

<div class="text-field">
  <%= f.label :check_out %> 
  <%= f.text_field :check_out, placeholder: "      dd/mm/yy", id:"add_flatpicker", style:"width:10vw;"%>
</div>

<br>

<div class="text-field">
  <%= f.label :number_of_guests %>
  <%= f.text_field :number_of_guests, placeholder: "   #", style:"width:3vw;" %>
</div> 

<br>

<script>
  
  flatpickr("#add_flatpicker", {});

</script>

app/views/reservations/new.html.erb
<div class="d-flex justify-content-center">

  <%= form_for [@listing, @reservation] do |f| %> 

<%= render partial: '/reservations/form', locals: { f: f } %>

<%= f.submit %> 

<% end %> 

</div>

app/views/reservations/show.html.erb
  <br><br> 

<div class=container>
 <div class=row>
  <div class="d-flex col-md-6">
  <div style="margin: auto">
  <div> <%= image_tag @listing.avatar.url if @listing.avatar? %> </div> 
  <br>
  <div> Check In: <br><%= @reservation.check_in %> </br> </div>
  <br>
  <div> Check Out: <br><%= @reservation.check_out %> </br> </div>
  <br>
  <div> Total $<br><%= @reservation.total_price %> </br> </div> 
  <br>
  <br>
  <div> <%= button_to "cancel", listing_reservation_path(@reservation), method: :destroy%> </div>
  </div>
  </div>


  <div class="demo-frame col-md-6">
 <br><br>
      <%= form_for :checkout_form, url: checkout_path, html: { id: "cardForm"} do |form| %>
      
      <%= form.hidden_field "token", value: @client_token %>

    
      <%= form.label :card_number, "Credit Card Number", html: {class: "hosted-fields--label"} %>
      <div id="card-number" class="hosted-field"></div>

      <%= form.label :expiration_date, "Expiration Date", html: {class: "hosted-fields--label"} %>
      <div id="expiration-date" class="hosted-field"></div>

      <%= form.label :cvv, "CVV", html: {class: "hosted-fields--label"} %>
      <div id="cvv" class="hosted-field"></div>

      <%= form.hidden_field "payment_method_nonce" %>

      <div class="button-container">
        <%= form.submit "Purchase", disabled: true, class: "btn btn-primary", id: "submit-payment-btn" %>


      </div>
    <% end %>
  </div>


 </div>
</div>
  <!-- Load the Client component. -->
  <script src="https://js.braintreegateway.com/web/3.6.3/js/client.min.js"></script>

  <!-- Load the Hosted Fields component. -->
  <script src="https://js.braintreegateway.com/web/3.6.3/js/hosted-fields.min.js"></script>


<script>

var form = document.querySelector('#cardForm');
var submit = document.querySelector("#submit-payment-btn");
var authorization = '<%= @client_token %>';

braintree.client.create({
  // Replace this with your own authorization.
  authorization: authorization
}, function (clientErr, clientInstance) {
  if (clientErr) {
    // Handle error in client creation
    return;
  }

  braintree.hostedFields.create({
    client: clientInstance,
    styles: {
      'input': {
        'font-size': '14pt'
      },
      'input.invalid': {
        'color': 'red'
      },
      'input.valid': {
        'color': 'green'
      }
    },
    fields: {
      number: {
        selector: '#card-number',
        placeholder: '4111 1111 1111 1111'
      },
      cvv: {
        selector: '#cvv',
        placeholder: '123'
      },
      expirationDate: {
        selector: '#expiration-date',
        placeholder: '10/2019'
      }
    }
  }, function (hostedFieldsErr, hostedFieldsInstance) {
    if (hostedFieldsErr) {
      // Handle error in Hosted Fields creation
      return;
    }

    submit.removeAttribute('disabled');

    form.addEventListener('submit', function (event) {
      event.preventDefault();

      hostedFieldsInstance.tokenize(function (tokenizeErr, payload) {
        if (tokenizeErr) {
          // Handle error in Hosted Fields tokenization
          return;
        }

        // Put `payload.nonce` into the `payment_method_nonce` input, and then
        // submit the form. Alternatively, you could send the nonce to your server
        // with AJAX.
        document.querySelector('input[name="checkout_form[payment_method_nonce]"]').value = payload.nonce;
        form.submit();
      });
    }, false);
  });
});

</script>

<%= form_for :checkout_form, url: braintree_checkout_path, html: { id: "cardForm"} do |form| %> <% end %>