config/routes.rb
Rails.application.routes.draw do
  resources :passwords, controller: "clearance/passwords", only: [:create, :new]
  resource :session, controller: "clearance/sessions", only: [:create]
  root "welcome#index"
  resources :users, controller: "users", only: [:create, :edit] do
    resource :password,
      controller: "clearance/passwords",
      only: [:create, :edit, :update]
  end

 resources :listings do 
   resources :reservations
  end 

  resources :users 
    # resources :listings, only: [:create, :new, :edit, :destroy, :show]



  get "/sign_in" => "clearance/sessions#new", as: "sign_in"
  delete "/sign_out" => "clearance/sessions#destroy", as: "sign_out"
  get "/sign_up" => "clearance/users#new", as: "sign_up"
  get "/auth/:provider/callback" => "sessions#create_from_omniauth"
  post "verification/:id" => "listings#verify", as: "verify"
  post "/listings/:listing_id/reservations/:id" => "reservations#destroy", as: "delete"
  post "/listings/:listing_id/reservations/:id/checkout" => "reservations#checkout", as: "checkout"

 post "/search"  => "listings#search"

  get 'braintree/new'
  post 'braintree/checkout'
  post 'braintree/new'




  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>artbnb</title>
    
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= csrf_meta_tags %>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/flatpickr/4.3.2/themes/airbnb.css">
   
    <meta name="viewport" content="width=device-width, initial-scale=1">
  </head>

<body>

<nav class="navbar navbar-expand-lg navbar-light bg-light">
              <a class="navbar-brand align_navbar" style=" margin-right: 30px;
    margin-left: 7px;" href="http://localhost:3000/">Artbnb</a>

                  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
              </button>

              <div class="collapse navbar-collapse" id="navbarSupportedContent">
               
                <ul class="navbar-nav mr-auto">
                
                  <%= form_tag(search_path,{class: "form-inline my-2 my-lg-0",}) do %>
                    <%= text_field_tag :location, nil , :placeholder => 'Try "New York City"', :class => "form-control mr-sm-2", :id => "hello", :list => "location_list" %>
                    <datalist id="location_list">
                     <!--  <option value="Okinawa"></option> -->
                    </datalist>
                    <%= text_field_tag :min_price , nil, placeholder: 'minimum price per night', :class => "form-control mr-sm-2 short_input_box" %>
                    <%= text_field_tag :max_price , nil, placeholder: 'maximum price per night', :class => "form-control mr-sm-2"%>
                    <%= submit_tag 'submit', :class => "btn btn-outline-success my-2 my-sm-0" %>
                  <% end %>

                  <div style="text-align: left; margin-left: 2vw;">
            </div>

                  <li class="nav-item active align_navbar">
                    <a class="nav-link" href="http://localhost:3000/listings/new"> Become a host    <span class="sr-only">(current)</span></a>
                  </li>

                  <br> <br>

                  
                         <% if signed_in? %>
                         <li class="nav-item active align_navbar">
                            <a class="nav-link">
                             <%= current_user.email %>
                            </a>
                         </li>   
                            
                         <li class="nav-item active align_navbar">
                            <a class="nav-link">
                              <%= button_to "Sign out", sign_out_path, method: :delete %>
                            </a>
                         </li>                        
                      
                      
                      <% else %>
                        <li class="nav-item active align_navbar">
                            <a class="nav-link" href=<%=sign_up_path%> >Sign Up </a>
                        </li>
                        <li class="nav-item dropdown active align_navbar">
                            <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                             Sign in
                            </a>
                            <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                            <a class="dropdown-item" href=<%=sign_in_path%> >Sign in</a>
                            <div class="dropdown-divider"></div>
                            <a class="dropdown-item" href="/auth/facebook">Connect via Facebook</a>
                            
                            </div>
                        </li>
                    <% end %>
                 </li>

               </ul>
              </div>
            </nav>


  <div id="flash">
    <% flash.each do |key, value| %>
      <div id="flash_<%= key %>" class="alert <%= flash_class(key).to_s %> "><%=h value %></div>
    <% end %>
 </div>
     <script src="https://cdnjs.cloudflare.com/ajax/libs/flatpickr/4.3.2/flatpickr.js"></script>
    <%= yield %>
</body>
  
   
</html>